ARG NODE_VERSION=16

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn lerna bootstrap
RUN rm -rf /app/packages/server/dist/ && yarn build

EXPOSE $SERVER_PORT
CMD [ "node", "packages/server/dist/index.js" ]
