version: "3.8"

services:
  postgres:
    container_name: prakticum-postgres
    image: postgres:14
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data

  server:
    container_name: prakticum-server
    image: ghcr.io/tsharon-byte/28_mf_teamwork_01/server:b13629df1bf973fbac5f762ca42167050197e8ba
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      NODE_ENV: ${ENV}
      AUTH_URL: ${AUTH_URL}
    depends_on:
      - postgres
      - nginx
    command: ["./wait-for-it/wait-for-it.sh", "${POSTGRES_HOST}:${POSTGRES_PORT}", "--", "node", "packages/server/dist/index.js"]

  nginx:
    container_name: prakticum-nginx
    image: ghcr.io/tsharon-byte/28_mf_teamwork_01/nginx:b13629df1bf973fbac5f762ca42167050197e8ba
    build:
      context: .
      dockerfile: Dockerfile.ginx
      args:
        DOMAIN: siberians-bomberman-28.ya-praktikum.tech
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/certs:/certs
    environment:
      - DOMAIN=siberians-bomberman-28.ya-praktikum.tech

  pgadmin:
    container_name: prakticum-pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 8088
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  pgadmin-data:
