export const RETRIEVE_USER_URL = 'auth/user/'
export const RETRIEVE_RESOURCE_URL = 'resources/{path}/'
export const CHANGE_AVATAR_URL = 'user/profile/avatar/'
export const CHANGE_PASSWORD_URL = 'user/password/'
export const RETRIEVE_CHATS_URL = 'chats/'
export const CHAT_LIST_URL = 'chats/'
